[This tree is taken from Wang-Kumar-Hedges, 1999. Unit is million years. (?)]
[Additional data from Hedges 2002.]
[Fugu, Danio div time is from Thomas and Touchman 2002 (reference is fish-mammal 0.450); C.elegans and C.briggsae div time is from Cochlan and Wolfe, 2002 (ref is nematode-arthropod 1.000); Arthropods and mammals as well as Nematodes and rest is approximately as in Wang and Kumar; Mouse and Human I guess is from Arnason.]
(
  (CAEEL:0.09,CBRIGG:0.09):1.01, 
  (DROME:0.990, 
    ((MOUSE:0.110, HUMAN:0.110):0.340[&&BEEP S=Mammals],
     (FUGU:0.290,DRERIO:0.290):0.160[&&BEEP S=Teleost]):0.540):0.110); 
